# Generated by Django 5.1.1 on 2024-09-17 07:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название объекта', max_length=250, verbose_name='Наименование объекта')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('measurement_unit', models.CharField(help_text='Укажите единицу измерения', max_length=12, verbose_name='Единица измерения')),
                ('amount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Введите количество больше 0.')], verbose_name='Количество')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('note', models.TextField(verbose_name='Комментарий')),
                ('buyer', models.ForeignKey(help_text='Выберите МОЛ', on_delete=django.db.models.deletion.PROTECT, to='items.buyer')),
                ('aim', models.ForeignKey(help_text='Выберите объект', on_delete=django.db.models.deletion.PROTECT, to='items.objects')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
                'ordering': ('name',),
            },
        ),
    ]
